### ISSUE TITLE
Syntax Errors in index.js

### ISSUE THREAD

**Issue by shivanraptor** [guillaumeteillet/create-your-own-facebook-messenger-bot-platform-ec2-aws#1]
Using NodeJS v0.10.48 ( installed via `n stable` in root environment ), the code runs with the following errors ( `node index.js` ) : 

```
const express = require('express');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

When using `npm --harmony index.js`, it shows another error:

```
app.get('/webhook', (req, res) => {
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

When I try **not** using root environment, opening the certificate returns "Permission Denied".

Please help.

**Comment by shivanraptor** [comment]
Additional information:
- Using Amazon Linux (not Ubuntu)
`npm version` returns:

```
{ http_parser: '1.2',
  node: '0.10.48',
  v8: '3.14.5.11',
  ares: '1.9.0-DEV',
  uv: '0.10.34',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e-fips',
  npm: '1.3.6',
  guillaumeteillet: '0.0.1' }
```
